{% set name = "ndpyramid" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndpyramid-{{ version }}.tar.gz
  sha256: 74772cb834ab1539ee0e8c7cde503fbf4fcf5ac54869c7cd37548d8b734858d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - cf_xarray
    - numpy
    - python >=3.8
    - xarray
    - xarray-datatree >=0.0.4
    - zarr

test:
  imports:
    - ndpyramid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carbonplan/ndpyramid
  summary: A small utility for generating ND array pyramids using Xarray and Zarr.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - jhamman
    - norlandrhagen
