{% set name = "ndpyramid" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndpyramid-{{ version }}.tar.gz
  sha256: ae710c646a55adf203eb6120d6e77a55949c5c8a4a79e121a22ab0d8ac163c02

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - cf_xarray
    - pydantic>=1.10
    - pyproj
    - python >=3.9
    - rasterio
    - xarray
    - xarray-datatree >=0.0.11
    - zarr

test:
  imports:
    - ndpyramid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carbonplan/ndpyramid
  summary: A small utility for generating ND array pyramids using Xarray and Zarr.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - jhamman
    - norlandrhagen
    - maxrjones
