{% set name = "ndpyramid" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ndpyramid-{{ version }}.tar.gz
  sha256: e816adb537266d70375f3e64f351d7c6f094d66885262319d9f914e692e0a2fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools-scm
  run:
    - cf_xarray
    - numpy <2.0.0
    - pydantic >=1.10
    - pyproj
    - python >=3.10
    - rasterio
    - xarray >=2024.10.0
    - zarr

test:
  imports:
    - ndpyramid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carbonplan/ndpyramid
  summary: A small utility for generating ND array pyramids using Xarray and Zarr.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - jhamman
    - norlandrhagen
    - maxrjones
