{% set name = "ndpyramid" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ndpyramid-{{ version }}.tar.gz
  sha256: 7f7753fb6f590b0b4441d238089ed19cae5d9d777053eaa514be528d0825458e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - cf_xarray
    - numpy <2.0.0
    - pydantic >=1.10
    - pyproj
    - python >=3.9
    - rasterio
    - xarray
    - xarray-datatree >=0.0.11
    - zarr

test:
  imports:
    - ndpyramid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/carbonplan/ndpyramid
  summary: A small utility for generating ND array pyramids using Xarray and Zarr.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - jhamman
    - norlandrhagen
    - maxrjones
